// Placeholder components for CEO templates
export { default as CeoAddDepartment } from './CeoAddDepartment'
export { default as CeoManageDepartment } from './CeoManageDepartment'
export { default as CeoAddDivision } from './CeoAddDivision'
export { default as CeoManageDivision } from './CeoManageDivision'
export { default as CeoCustomersManage } from './CeoCustomersManage'
export { default as CeoJobCardDashboard } from './CeoJobCardDashboard'
export { default as CeoLocationAnalytics } from './CeoLocationAnalytics'
export { default as CeoGeofenceManagement } from './CeoGeofenceManagement'
export { default as CeoViewAttendance } from './CeoViewAttendance'
export { default as CeoEmployeeFeedback } from './CeoEmployeeFeedback'
export { default as CeoManagerFeedback } from './CeoManagerFeedback'
export { default as CeoNotifyManager } from './CeoNotifyManager'
export { default as CeoNotifyEmployee } from './CeoNotifyEmployee'
export { default as CeoManagerLeave } from './CeoManagerLeave'
export { default as CeoEmployeeLeave } from './CeoEmployeeLeave'
export { default as CeoViewProfile } from './CeoViewProfile'
