# Generated by Django 4.2.25 on 2025-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chatgroup_chatgroupmember_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscalendar',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
