# Generated by Django 4.2.25 on 2025-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_businesscalendar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_general_assignment',
            field=models.BooleanField(default=False, help_text='If true, this job card is assigned to all employees'),
        ),
    ]
